### ISSUE TITLE
Competitor List

### ISSUE THREAD

**Issue by pluginbazar-main** [Becreative-Marketing-Limited/wp-poll#11]
Please create a list of competitor plugins of WP Poll and put their link with some other data. I am adding one as a sample.

1. [TS Poll](https://wordpress.org/plugins/poll-wp/)
2. [YOP Poll](https://wordpress.org/plugins/yop-poll/)
3. [Poll Maker](https://wordpress.org/plugins/poll-maker/)
4. [Poll, Survey & Quiz Maker Plugin by Opinion Stage](https://wordpress.org/plugins/social-polls-by-opinionstage/)
5. [Contact Form by WPForms](https://wordpress.org/plugins/wpforms-lite/)
6. [WP-Polls](https://wordpress.org/plugins/wp-polls/)
7. [Democracy Poll](https://wordpress.org/plugins/democracy-poll/)
8. [Formidable Form Builder](https://wordpress.org/plugins/formidable/)

**Comment by masumwp01** [comment]
1. TS Poll
	By totalsoft
	
	URL: https://wordpress.org/plugins/poll-wp/
	
	a. Ability to add images.
	b. Ability to add videos (YouTube & Vimeo).
	c. Availability to see which answer was chosen 
	d.User information form
	e.Possibility to block re-voting using various possibilities ” for example, Cookie + IP together, Cookie + vote again in a day, IP + vote again in a day 
	f.Customize results fragments (votes, percentage).
	g.Customize typography settings (font family, image size, video size).
	h.Several polls on the same page.
	i.Allow users to click on the link to show results before voting.

2.	YOP Poll
	By yourownprogrammer
	
	URL: https://wordpress.org/plugins/yop-poll/
	
	a. Poll scheduling: programs each poll to start/end on a certain date.
		You can simultaneously run multiple polls. This option can be used to schedule your polls one after another.
		
	b. Display polls: you can choose to display one or more polls on your website by 
		simply adding the corresponding poll ID. 
		You can also decide on a random display of your active polls.	
		
	c. Add custom fields – is a complex option that you can use to ask for 
		additional information from your voters, information that you can then export and use for.

	d. Vote permissions: – limits the voting accessibility to guests, registered users 
		or both, or blocks user access by cookie, IP, and username.
		
	e. Logs and bans – user logs and bans can be seen in the admin section. You can ban 
		users by email, username, and IP and you can set the limitation preferences for all your polls or for just one of them.
		
3. Poll Maker
	By Poll Maker Team	

	URL: https://wordpress.org/plugins/poll-maker/
	
	a. POLL TYPES : Choosing,Rating,Voting ,Dropdown,Range,VS (versus).
	b. Multivote functionality
	c.NOTIFY ADMIN BY EMAIL.
	d.REDIRECTION (INDIVIDUAL AND GLOBAL): Redirection is a super-effective technique to 
		boost your website traffic. Attract your website visitors via engaging polls and after voting, redirect them to another webpage
	e.SCHEDULE POLL
	f.LIMIT BY USER ROLES
	g.Style settings.
	h.Ability to add custom option
	i.Vote reason option
	j. integration:
		MailChimp integration
		Campaign Monitor integration
		Zapier integration
		Google sheet integration
		GamiPress integration
		SMTP integration
	k.Send mail to user	

4. Poll, Survey & Quiz Maker Plugin by Opinion Stage
	By OpinionStage.com	

	URL: https://wordpress.org/plugins/social-polls-by-opinionstage/
	
	a.Use Survey and quiz branch logic that lets you determine which question is asked 
		next based on the answer to the previous question.
		
	b. Embed in a single post/page or display in a sidebar or section placement.
	c.Popup the items automatically when users enters/exits the page.
	d.Responsive design that optimizes the display of polls, quizzes, and surveys in 
		desktops, tablets, and mobile devices.

5. Contact Form by WPForms – Drag & Drop Form Builder for WordPress
	By WPForms
	
	URL: https://wordpress.org/plugins/wpforms-lite/
	
6. WP-Polls
	By Lester 'GaMerZ' Chan
	
	URL: https://wordpress.org/plugins/wp-polls/
	
7. Democracy Poll
	By Kama	
	
	URL: https://wordpress.org/plugins/democracy-poll/
	
	a.a user can change his opinion when re-vote option is enabled.
	b.inserting new polls to any posts: the [demоcracy] (shortcode). A key in visual 
		editor is available for this function.
	c.showing a note under the poll: a short text with any notes to the poll or 
		anything around it.

8. Formidable Form Builder – Contact Form, Survey & Quiz Forms Plugin for WordPress
	By Strategy11

	URL: https://wordpress.org/plugins/formidable/
